version: '2'

services:

  api_engine:
    container_name: api_engine
    hostname: api_engine
    build: ./api_engine
    stdin_open: true
    tty: true
    ports:
      - "8081:8081"
    networks:
      my_net:
        ipv4_address: 172.20.0.20

  aa_player:
    build: ./aa_player
    stdin_open: true
    tty: true
    networks:
      my_net:

  aa_npc:
    build: ./aa_npc
    stdin_open: true
    tty: true
    networks:
      my_net:

  aa_registry:
    container_name: aa_registry
    ports:
       - "1600:1600"
       - "8000:8000"
    build: ./aa_registry
    stdin_open: true
    tty: true
    networks:
      my_net:
        aliases: 
            - aa_registry

  aa_engine:
    build: ./aa_engine
    stdin_open: true
    tty: true
    networks:
      my_net:

  front:
    container_name: front
    build: ./front
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      my_net:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27012:27017"
    networks:
        my_net:
          aliases: 
            - mongo_host

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - my_net

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - my_net
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
